# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: nodeserver
  tag: 1.0.0
  pullPolicy: IfNotPresent 
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
  readinessProbe: {}
  # Example (replace readinessProbe: {} with the following):
  # readinessProbe:
    # httpGet:
      # path: /ready
      # port: 8080
    # initialDelaySeconds: 3
    # periodSeconds: 5
  livenessProbe: {}
  # Example (replace livenessProbe: {} with the following)::
  # livenessProbe:
    # httpGet:
      # path: /live
      # port: 8080
    # initialDelaySeconds: 40
    # periodSeconds: 10  
service:
  name: Node
  type: ClusterIP
  servicePort: 8080
route:
  enabled: true
ingress:
  enabled: false
  appid:
    enabled: false
    # web or app - https://cloud.ibm.com/docs/services/appid?topic=appid-kube-auth
    requestType: web

#  host: hello
  namespaceInHost: true
  subdomain: containers.appdomain.cloud
  path: "/"
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  metrics:
    cpu:
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70
services:
base:
  enabled: false
  replicaCount: 1
  image:
    tag : v0.9.9
  weight: 100

istio:
  enabled: false
  weight: 100

vcsInfo:
  repoUrl: ""
  branch: ""

partOf: covidmanagement

connectsTo: ibm-tcs-hackathon-hospitals-backend

runtime: nodejs