{{- if .Values.route.enabled -}}
{{- $fullName := include "starter-kit.fullname" . -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "starter-kit.name" . }}
    helm.sh/chart: {{ include "starter-kit.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  to:
    kind: Service
    name: "{{  .Chart.Name }}-service"
    weight: 100
  port:
    targetPort: 8080-tcp
  # tls:
    # termination: edge
  wildcardPolicy: None
{{- end }}